using System;
using Interfaces;

namespace Core.Events
{
    public class ChatEvent : IEvent
    {
        public string RawInput { get; set; }         // The raw text input from the user (e.g. "/give stone 5")
        public string Message { get; set; }          // Displayed message (used if not a command, e.g. "Hello!")
        public string SenderId { get; set; }         // Unique ID or name of the sender
        public DateTime Timestamp { get; set; }      // When the message was sent
        public ChatEventType Type { get; set; }      // Type of the message: chat, command, system, etc.
    }

    public enum ChatEventType : byte
    {
        PlayerMessage,    // A normal chat message from a player
        Command,          // A command input (starts with "/")
        SystemMessage,    // A message generated by the system (e.g. "Player joined")
        DebugMessage,     // Developer/debug message
        Warning,          // A warning (e.g. missing parameters)
        Error             // An error (e.g. invalid command)
    }

}